name: mellazine
description: Shop direct from your celebrity.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  smooth_star_rating_null_safety: ^1.0.4+2
  intl: ^0.18.1
  persistent_bottom_nav_bar_v2: ^4.2.8
  animated_text_kit: ^4.2.2
  liquid_swipe: ^3.1.0
  badges: ^3.1.1
  objectbox: ^2.2.1
  objectbox_flutter_libs: ^2.2.1
  fluttertoast: ^8.2.2
  country_picker: ^2.0.20
  flutter_credit_card: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  # ObjectBox
  build_runner: ^2.4.6
  objectbox_generator: ^2.2.1

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/selling_now/
    - assets/payment_methods/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
